#
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
#
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 15s

scrape_configs:
  - job_name: 'slurm_exporter'
    scrape_interval:  30s
    scrape_timeout:   30s
    static_configs:
      - targets: ['__LOCAL_IP__:8080']
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['__LOCAL_IP__:9091']
  - job_name: 'prometheus_server'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'ec2_instances'
    scrape_interval: 5s
    ec2_sd_configs:
      - port: 9100
        region: __AWS_REGION__
        refresh_interval: 10s
        filters:
          - name: instance-state-name
            values:
              - running
          - name: tag:Name
            values:
              - Compute
              - Login
