#
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
#
services:
    prometheus-node-exporter:
        container_name: node-exporter
        network_mode: host
        pid: host
        restart: unless-stopped
        volumes:
            - '/:/host:ro,rslave'
        image: quay.io/prometheus/node-exporter:v1.9.1
        command:
            - '--path.rootfs=/host'